server:
  port: 4399
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
spring:
  profiles:
    active: native
  application:
    name: mortal-config-server
  cloud:
    config:
      server:
        native:
          search-locations: D:\soft\Git\repository\mortal\mortal-config
#        git:
#          uri: https://github.com/IamaMortal/mortal-config.git
#          username: IamaMortal
#          password: king@620*quan